name: Primeiro workflow Linuxtips
#evento
on:
    push:
        branches:
            - main
#Trigger
jobs:
    giropops:
        runs-on: ubuntu-latest
        steps:
            - name: Confere versao do Ubuntu
              run: cat /etc/os-release
            
            - name: Exibir mensagem
               run: echo "Estou fazendo o curso de Github Actions da Linuxtips"
            