name: Lendo arquivo entre Jobs

on:
    push:
        branches:
            - main

jobs:
    jobs_1:
        runs-on: ubuntu-latest
        steps:
            - name: Confere versao do Ubuntu
              run: cat /etc/os-release
            
            - name: Exibe uma Mensangem
              run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > ${{ github.workspaces }}mensagem.txt

            - uses: actions/upload-artifact@v4
              with:
                name: strigus-upload
                path: ${{ github.workspaces }}mensagem.txt
            
    jobs_2:
        runs-on: ubuntu-latest
        needs: jobs_1
        steps:
            - name: Listar arquivo mensagem.txt
              run:  ls -lha
                       
            - uses: actions/download-artifact@v4
              with:
                name: strigus-upload
                path: mensagem.txt
            
            - name: Listar arquivo mensagem.txt
              run:  ls -lha && ls ./strigus
            
            - name: Movimenta arquivo mensagem.txt para fora da pasta strigus
              run: mv strigus/mensagem.txt . && rm -rf ./strigus
            
            - name: Ver o conteudo do diretorio
              run: ls -lha
            
            - name: Exibir conteudo de mensagem.txt
              run: cat mensagem.txt